import type { NextPage } from 'next';
import {sanityClient, urlFor} from "../client";
import {Post} from "../typings";

import Head from 'next/head'
import Header from "../components/Header";
import Blog from "../components/Blog";
import SinglePost from "../components/SinglePost";
import Footer from "../components/Footer";

interface Props{
  posts: [Post];
}

const Home = ({posts}: Props) => {
  
  return (
    <>
      <Head>
        <title>Kodao.io Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Blog posts={posts}/>
      <Footer/>
    </>
  )
}

export const getServerSideProps = async() => {

  const query = `*[_type == "post"]{
    _id,
     title,
     slug,
     mainImage{asset->{url},alt},
     body,
     excerpt,
     publishedAt,
     "categories": categories[]->title,
     "authorName":author->name,
   }`

   const posts = await sanityClient.fetch(query);

   return{
     props: {
       posts
     }
   }
}
export default Home
